assets:
  css:
    - bundles/os2displayexchange/assets/build/os2displayexchange.min.css
  js_prod:
    - bundles/os2displayexchange/assets/build/os2displayexchange.min.js

modules:
  exchangeModule:
    files:
      - bundles/os2displayexchange/apps/os2displayExchangeModule/os2displayExchangeModule.js
      - bundles/os2displayexchange/apps/os2displayExchangeModule/os2displayEmailListTool.js

apps:
  ikApp:
    dependencies:
      - os2displayExchangeModule
