services:
  os2display.exchange.service:
    class: Os2Display\ExchangeBundle\Service\ExchangeService
    arguments: ['@os2display.exchange.cache', '@os2display.exchange.web_service', '@doctrine.orm.entity_manager', false, 1800]
    tags:
      - { name: kernel.event_listener, event: ik.cron, method: onCron }
    public: true

  os2display.exchange.web_service:
    class: Os2Display\ExchangeBundle\Service\ExchangeWebService
    arguments: ['@os2display.exchange.soap_client']
    public: true

  os2display.exchange.soap_client:
    class: Os2Display\ExchangeBundle\Service\ExchangeSoapClientService
    arguments: ['%os2display_exchange.host%', '%os2display_exchange.user%', '%os2display_exchange.password%', 'Exchange2010']
    public: true

  os2display.exchange.cache:
    class: Doctrine\Common\Cache\FilesystemCache
    arguments: ['%kernel.cache_dir%']
    public: true
